name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - 'MagicUtilsReleases'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Print GitHub ref
        run:
          echo "This run triggered by ref: $GITHUB_REF"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Jar to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
